[build.environment]
NPM_FLAGS = "--version"

[build]
command = 'npx pnpm install --store=node_modules/.pnpm-store && npm run build'
publish = 'dist'

[functions]
external_node_modules = ["sharp"]
included_files = ["node_modules/sharp/**/*"]
